repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: git://github.com/marick/pre-commit-hooks
    rev: a4bfe84e14025ee174a48cbe3069b14f9421efb6
    stages: [commit, push]
    hooks:
    -   id: only-branch-pushes
        args: [prevent, ^(production|master)$]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.11.2
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.0
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.7.1
    hooks:
    -   id: add-trailing-comma
-   repo: meta
    hooks:
    -   id: check-useless-excludes
